### ISSUE TITLE
When I click on the "Send Money" button, the app closes. 2.0.05

### ISSUE THREAD

**Issue by Wjxfi** [nighthawk-apps/nighthawk-wallet-android#138]
I don't have a zec

FATAL EXCEPTION: main
Process: com.nighthawkapps.wallet.android, PID: 3399
java.lang.IllegalArgumentException: Zatoshi must be in the range [0, 2100000000000000]
	at cash.z.ecc.android.sdk.model.Zatoshi.<init>(Zatoshi.kt:12)
	at cash.z.ecc.android.sdk.model.Zatoshi.minus(Zatoshi.kt:17)
	at com.nighthawkapps.wallet.android.ui.send.SendEnterAmountFragment.onBalanceUpdated(SendEnterAmountFragment.kt:254)
	at com.nighthawkapps.wallet.android.ui.send.SendEnterAmountFragment.access$onBalanceUpdated(SendEnterAmountFragment.kt:29)
	at com.nighthawkapps.wallet.android.ui.send.SendEnterAmountFragment$onViewCreated$1$1$2$1.emit(SendEnterAmountFragment.kt:53)
	at com.nighthawkapps.wallet.android.ui.send.SendEnterAmountFragment$onViewCreated$1$1$2$1.emit(SendEnterAmountFragment.kt:52)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.nighthawkapps.wallet.android.ui.send.SendEnterAmountFragment$onViewCreated$1$1$2.invokeSuspend(SendEnterAmountFragment.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1.onStateChanged(RepeatOnLifecycle.kt:106)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:96)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:703)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3151)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3142)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6f2524f, Dispatchers.Main.immediate]

**Device**

miui 13.5 
android 12 
api 31

**Comment by hok7z** [comment]
Same problem in android 13
