### ISSUE TITLE
App crashes after upgrade, then works fine

### ISSUE THREAD

**Issue by gmale** [nighthawk-apps/nighthawk-wallet-android#39]
There still appears to be an issue where the app crashes after the first time it completes a scan on upgrade. This crash is related but different than the previous one that was fixed as part of https://github.com/zcash/zcash-android-wallet/issues/258

**Comment by gmale** [comment]
I can't assign work on this repository but I will try to reproduce and correct this issue, as discussed with @nighthawk24

**Comment by nighthawk24** [comment]
Here are the steps to reproduce:

Step 1: Install Nighthawk Android 1.0.17
Step 2: Restore a wallet with funds
Step 3: Send MAX funds to a Z-address
Step 4: Upgrade Nighthawk to 1.0.18/master branch
Step 5: App Crashes on Start with the following log

The app functions well on 2nd launch, and a broken/tx wallet requires a Rescan to fix the transactions.

   ```
 --------- beginning of crash
2021-05-03 14:47:19.466 19911-19911/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nighthawkapps.wallet.android, PID: 19911
    cash.z.ecc.android.sdk.exception.InitializerException$MissingAddressException: Expected a shielded address for this wallet but failed to find one. This usually means that wallet setup happened incorrectly. If this problem persists, a workaround might be to go to settings and WIPE the wallet and rescan. Doing so will restore any missing address information. Meanwhile, please report that this happened so that the root issue can be uncovered and corrected.
        at cash.z.ecc.android.sdk.block.CompactBlockProcessor$getShieldedAddress$2.invokeSuspend(CompactBlockProcessor.kt:752)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by nighthawk24** [comment]
Ran in to another Scan Failure when resuming the updated app after doing a rescan.

```
2021-05-03 19:55:28.845 21173-21173/? I/.wallet.androi: Not late-enabling -Xcheck:jni (already on)
2021-05-03 19:55:29.267 21173-21173/? I/.wallet.androi: Unquickening 12 vdex files!
2021-05-03 19:55:29.273 21173-21173/? W/.wallet.androi: Unexpected CPU variant for X86 using defaults: x86
2021-05-03 19:55:32.579 21173-21173/com.nighthawkapps.wallet.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-05-03 19:55:32.582 21173-21173/com.nighthawkapps.wallet.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-05-03 19:55:32.754 21173-21277/com.nighthawkapps.wallet.android D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2021-05-03 19:55:32.765 21173-21277/com.nighthawkapps.wallet.android D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2021-05-03 19:55:32.777 21173-21277/com.nighthawkapps.wallet.android D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2021-05-03 19:55:33.105 21173-21173/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-05-03 19:55:33.108 21173-21173/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-05-03 19:55:35.383 21173-21173/com.nighthawkapps.wallet.android I/TetheringManager: registerTetheringEventCallback:com.nighthawkapps.wallet.android
2021-05-03 19:55:35.996 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background concurrent copying GC freed 5766(409KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3205KB/6410KB, paused 7.819ms total 201.149ms
2021-05-03 19:55:36.111 21173-21254/com.nighthawkapps.wallet.android D/HostConnection: HostConnection::get() New Host Connection established 0xed1e2440, tid 21254
2021-05-03 19:55:36.136 21173-21254/com.nighthawkapps.wallet.android D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
2021-05-03 19:55:36.184 21173-21254/com.nighthawkapps.wallet.android W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2021-05-03 19:55:36.185 21173-21254/com.nighthawkapps.wallet.android D/EGL_emulation: eglCreateContext: 0xed1e2a60: maj 3 min 0 rcv 3
2021-05-03 19:55:36.192 21173-21254/com.nighthawkapps.wallet.android D/EGL_emulation: eglMakeCurrent: 0xed1e2a60: ver 3 0 (tinfo 0xed4d3c70) (first time)
2021-05-03 19:55:36.257 21173-21254/com.nighthawkapps.wallet.android I/Gralloc4: mapper 4.x is not supported
2021-05-03 19:55:36.262 21173-21254/com.nighthawkapps.wallet.android D/HostConnection: createUnique: call
2021-05-03 19:55:36.263 21173-21254/com.nighthawkapps.wallet.android D/HostConnection: HostConnection::get() New Host Connection established 0xed1e2bb0, tid 21254
2021-05-03 19:55:36.264 21173-21254/com.nighthawkapps.wallet.android D/goldfish-address-space: allocate: Ask for block of size 0x100
2021-05-03 19:55:36.264 21173-21254/com.nighthawkapps.wallet.android D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3fda05000 size 0x2000
2021-05-03 19:55:36.284 21173-21254/com.nighthawkapps.wallet.android D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
2021-05-03 19:55:36.626 21173-21173/com.nighthawkapps.wallet.android I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
2021-05-03 19:55:37.164 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.164 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.164 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setUseSessionTickets(Z)V (greylist-max-q, reflection, denied)
2021-05-03 19:55:37.164 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.164 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.165 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (greylist-max-q, reflection, denied)
2021-05-03 19:55:37.165 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.165 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setAlpnProtocols([B)V (greylist-max-q, reflection, denied)
2021-05-03 19:55:37.420 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist-max-q,core-platform-api, reflection, denied)
2021-05-03 19:55:37.420 21173-21443/com.nighthawkapps.wallet.android W/.wallet.androi: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (greylist-max-q, reflection, denied)
2021-05-03 19:55:37.575 21173-21247/com.nighthawkapps.wallet.android I/.wallet.androi: Waiting for a blocking GC ProfileSaver
2021-05-03 19:55:37.583 21173-21247/com.nighthawkapps.wallet.android I/.wallet.androi: WaitForGcToComplete blocked ProfileSaver on RunEmptyCheckpoint for 8.432ms
2021-05-03 19:55:38.492 21173-21254/com.nighthawkapps.wallet.android I/OpenGLRenderer: Davey! duration=861ms; Flags=0, IntendedVsync=60392339938720, Vsync=60392339938720, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=60392341940479, AnimationStart=60392342049479, PerformTraversalsStart=60392342173479, DrawStart=60393119558479, SyncQueued=60393197037479, SyncStart=60393199376479, IssueDrawCommandsStart=60393199526479, SwapBuffers=60393200875479, FrameCompleted=60393203580479, DequeueBufferDuration=258000, QueueBufferDuration=1277000, GpuCompleted=144115222452437075, 
2021-05-03 19:55:38.721 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background young concurrent copying GC freed 17547(1110KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 5712KB/6410KB, paused 1.430ms total 764.840ms
2021-05-03 19:55:39.306 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background concurrent copying GC freed 8322(450KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5582KB/10MB, paused 646us total 249.045ms
2021-05-03 19:56:02.950 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background young concurrent copying GC freed 34020(1684KB) AllocSpace objects, 2(1840KB) LOS objects, 21% free, 8711KB/10MB, paused 1.343ms total 181.831ms
2021-05-03 19:56:05.394 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background young concurrent copying GC freed 21014(1016KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 10MB/10MB, paused 808us total 133.594ms
2021-05-03 19:56:06.415 21173-21216/com.nighthawkapps.wallet.android I/.wallet.androi: Background concurrent copying GC freed 42353(2385KB) AllocSpace objects, 11(2168KB) LOS objects, 49% free, 6102KB/11MB, paused 560us total 196.069ms

```

**Comment by gmale** [comment]
This is a separate issue but we can look at it as part of this work.

The good news is the recent work in the SDK to bubble up errors and provide better feedback on critical problems is working. Previously, these would have just crashed without a message.

The "database disk image malformed" is an awful bug. Under the hood, it is over-used and does not actually mean that the database file is corrupted. It can still be opened and used and read with a sqlite browser. Getting to the bottom of whether it is Rusqlite on the Rust side or Room on the Android side that is throwing the error would require some effort and might help.

However, what I've noticed is this is more likely to happen if Rust and Kotlin are trying to use the database at the same time. This is part of the reason why I started making [DB access more sequential](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt#L473-L498) as a temporary fix. The real fix is to stop having Rust do anything with the database, directly, and allow Room to control it all. Which also has the added benefit that Room could observe the database and generate events when tables change. Right now, we have to poll everything, instead, because Rust does all the write operations.

Once you hit this error, you'll keep hitting it until you do a WIPE. So the key to troubleshooting it is to identify what was happening when the error first presented itself (and not confuse it with subsequent DB actions AFTER the problem was created). It sounds like the screen you were on was reading or writing the DB at the same time that the processor was checking for new blocks.

Next steps:
- I think we should nail down and fix the first crash that started this github issue
- after that, we can take a look at what the HomeFragment is doing that could cause it touch the DB during a scan. Then we should probably put that behind a mutex or something and maybe we can do that at the SDK level.
- for this particular wallet, it is bricked until a WIPE is done. So I'll update those error messages to say "if this problem persists, rescan the wallet from settings and chose WIPE to fully restore the DB." Of course, that should be a last resort. Users will continue to get into this situation if we don't spot and correct the root cause.
- on the longer horizon, the data access api will allow us to move all the database operations out of Rust. That work has progressed a lot and is ready for the next phase.

**Comment by gmale** [comment]
Found the root issue of the crash related to this ticket:
>  Warning: did not drop the accounts table. It probably did not yet exist. due to: java.lang.RuntimeException: Error while dropping the accounts table: FOREIGN KEY constraint failed

I thought that a drop did not require relaxing foreign key constraints. So this should be fixable. Unfortunately, it takes a while to test because you have to trigger the upgrade flow but I'll put in the fix and start that process . . .

**Comment by nighthawk24** [comment]
Fixed with https://github.com/nighthawk-apps/nighthawk-wallet-android/pull/42
